### ISSUE TITLE
Hey! maybe look into into TextEdits smooth scroll?

### ISSUE THREAD

**Issue by boukew99** [SpyrexDE/SmoothScroll#1]
Hey! maybe look into into TextEdits smooth scroll?
They work with step of the Scrollbar, so maybe that is an easy way to do it too? 
Anyway I have no need for this right now, just trying to help.

**Comment by SpyrexDE** [comment]
You are right, the TextEdit node has a smooth scroll property, that you can be set to true. But that's it. It is only working for text editor boxes and the scroll still is way too rough. Also, you have absolutely no customization possibilities.
