### ISSUE TITLE
Make scroll framerate independent

### ISSUE THREAD

**Issue by SumianVoice** [SpyrexDE/SmoothScroll#26]
Currently, the framerate determines the speed, damping, friction etc. This means it's impossible to guess the actual end result people will get, since one person might have 30fps and another 500. High FPS results in very slow scroll with high friction, low FPS results in very fast scroll and less friction. 

To reproduce, you can change the max FPS in the project settings (enable advanced) to some small value like 30, then remove the limit and test again.

**Comment by SpyrexDE** [comment]
@HaroldLever Any idea how to properly implement framerate independency? My attempts with deltat time didn't really work out :/

**Comment by SpyrexDE** [comment]
Issue resolved by #34
