### ISSUE TITLE
General performance issue

### ISSUE THREAD

**Issue by SpyrexDE** [SpyrexDE/SmoothScroll#38]
Having a AMD Ryzen 9 3900X 12-Core CPU and a NVIDIA GeForce RTX 2080 Ti GPU im am only getting about `27 fps` at max in the example scene. As soon as I remove the scroll container from that scene it goes up to over 120fps again.

**Comment by HaroldLever** [comment]
I notice that too. I believe there's some problem with update_text(). I delete it and there's no more performance issue.
