### ISSUE TITLE
Scrolling via mouse wheel does not work when hovering over child controls

### ISSUE THREAD

**Issue by Xynonners** [SpyrexDE/SmoothScroll#46]
When using a normal ScrollContainer, scrolling works (horizontal) when using mousewheel when hovering over any area of the ScrollContainer. However, when using a SmoothScrollContainer, this doesn't seem to be the case.

**Comment by SpyrexDE** [comment]
This is probably due to the mouse filter setting of the child controls being `stop` instead of `pass`. If you can't figure it out yourself, please provide a minimal reproduction project.

**Comment by SpyrexDE** [comment]
I will close this issue due to inactivity. If the issue persists, please leave a comment and I will reopen the issue.
