### ISSUE TITLE
Stuttering on slow movement

### ISSUE THREAD

**Issue by SpyrexDE** [SpyrexDE/SmoothScroll#50]
When setting a low scroll speed/friction the content is not moving smoothly anymore, framerate independent.
Could have something to do with the resolution or coordinates being floating-point numbers.

https://github.com/SpyrexDE/SmoothScroll/assets/57133330/6e8b4b20-68b2-4fb8-bc01-285bfcfbccfc

**Comment by HaroldLever** [comment]
Perhaps unchecking snap_controls_to_pixel might help.
![image](https://github.com/SpyrexDE/SmoothScroll/assets/80692930/ea36bee7-8d37-4523-8bfa-41820d249824)

**Comment by SpyrexDE** [comment]
That worked, I added that to the sample project, but the user should definitely be told that.
I will add this to the readme as well.
